# Changelog for version 2.0 - Initial implementation

databaseChangeLog:
  #########################################
  # Service Request Module
  #########################################
  
  # Request status table
  - changeSet:
      id: 5
      author: JuanGonzalez
      comment: Creation of request status table
      changes:
        - sqlFile:
            path: ../scripts/schema/tables/request_status.sql
            relativeToChangelogFile: true
  
  # Services table
  - changeSet:
      id: 6
      author: JuanGonzalez
      comment: Creation of services table
      changes:
        - sqlFile:
            path: ../scripts/schema/tables/services.sql
            relativeToChangelogFile: true
  
  # Requesters table
  - changeSet:
      id: 7
      author: JuanGonzalez
      comment: Creation of requesters table
      changes:
        - sqlFile:
            path: ../scripts/schema/tables/requesters.sql
            relativeToChangelogFile: true
  
  # Requests table
  - changeSet:
      id: 8
      author: JuanGonzalez
      comment: Creation of requests table
      changes:
        - sqlFile:
            path: ../scripts/schema/tables/requests.sql
            relativeToChangelogFile: true

  # Detail request service table
  - changeSet:
      id: 9
      author: JuanGonzalez
      comment: Creation of detail request service table
      changes:
        - sqlFile:
            path: ../scripts/schema/tables/detail_request_service.sql
            relativeToChangelogFile: true
  
  # Initial data for request status
  - changeSet:
      id: 10
      author: JuanGonzalez
      comment: Insertion of initial request status data
      changes:
        - sqlFile:
            path: ../scripts/data/initial_request_status.sql
            relativeToChangelogFile: true
  
  # Tag to mark the end of version 1.0
  - changeSet:
      id: 11
      author: JuanGonzalez
      comment: Tag for version 1.0
      changes:
        - tagDatabase:
            tag: v1.0